### ISSUE TITLE
Docstring of phases displays phase descriptor

### ISSUE THREAD

**Issue by Minipada** [google/openhtf#877]
I'm trying to generate a sphinx documentation of my apps but the only output I get from my phase documentation is the phase descriptor class.

This is what I'm running:

```
#!/usr/bin/env python
"""OPENHTF based motor control test"""
from __future__ import division, print_function
import openhtf as htf

@htf.measures(htf.Measurement('hello_world_measurement'))
def hello_world(test):
  """A hello world test phase."""
  test.logger.info('Hello World!')
  test.measurements.hello_world_measurement = 'Hello Again!'


if __name__ == '__main__':
    print(hello_world.__doc__)
    pass
```

This is the output:

```
Phase function and related information.

  Attributes:
    func: Function to be called (with TestApi as first argument).
    options: PhaseOptions instance.
    plugs: List of PhasePlug instances.
    measurements: List of Measurement objects.
    extra_kwargs: Keyword arguments that will be passed to the function.
    code_info: Info about the source code of func.
```

I guess something is broken, do you know what it could be?
